---
title: "Replace with Main Title"
author: "Your Name"
date: "AUTOMATIC"
---


```{r echo=FALSE, message=FALSE}
# include this code chunk as-is to set options
knitr::opts_chunk$set(comment=NA, prompt=TRUE)
library(Rcmdr)
library(car)
library(RcmdrMisc)
```


```{r echo=FALSE}
# include this code chunk as-is to enable 3D graphs
library(rgl)
knitr::knit_hooks$set(webgl = hook_webgl)
```

```{r}
local({
  .PC <- princomp(~Age+BMI, cor=TRUE, data=diab)
  cat("\nComponent loadings:\n")
  print(unclass(loadings(.PC)))
  cat("\nComponent variances:\n")
  print(.PC$sd^2)
  cat("\n")
  print(summary(.PC))
  screeplot(.PC)

})
```

```{r}
.cluster <-  KMeans(model.matrix(~-1 + Age + BMI, diab), centers = 2, 
  iter.max = 10, num.seeds = 10)
.cluster$size # Cluster Sizes
.cluster$centers # Cluster Centroids
.cluster$withinss # Within Cluster Sum of Squares
.cluster$tot.withinss # Total Within Sum of Squares
.cluster$betweenss # Between Cluster Sum of Squares
biplot(princomp(model.matrix(~-1 + Age + BMI, diab)), xlabs = 
  as.character(.cluster$cluster))
remove(.cluster)
```

```{r}
HClust.1 <- hclust(dist(model.matrix(~-1 + Age+BMI, diab)) , method= "ward")
plot(HClust.1, main= "Cluster Dendrogram for Solution HClust.1", xlab= 
  "Observation Number in Data Set diab", 
  sub="Method=ward; Distance=euclidian")
```

```{r}
summary(as.factor(cutree(HClust.1, k = 2))) # Cluster Sizes
by(model.matrix(~-1 + Age + BMI, diab), as.factor(cutree(HClust.1, k = 2)), 
  colMeans) # Cluster Centroids
biplot(princomp(model.matrix(~-1 + Age + BMI, diab)), xlabs = 
  as.character(cutree(HClust.1, k = 2)))
```

